package com.example.ui.util

object AppStrings {
    fun t(key: String, lang: String = "ar"): String {
        val isAr = lang == "ar"
        return when (key) {
            "app_title" -> if (isAr) "مجموعة مدارس الأبرار" else "Groupe Scolaire Al Abrar"
            "brand_tag" -> "AL ABRAR GROUPE SCOLAIRE"
            "dashboard" -> if (isAr) "لوحة التحكم" else "Tableau de bord"
            "scanner" -> if (isAr) "الماسح الضوئي" else "Scanner QR"
            "students" -> if (isAr) "التلاميذ" else "Élèves"
            "rooms" -> if (isAr) "القاعات" else "Salles"
            "reports" -> if (isAr) "التقارير" else "Rapports"
            "settings" -> if (isAr) "إعدادات الموقع" else "Paramètres"
            "logout" -> if (isAr) "تسجيل الخروج" else "Déconnexion"
            "login" -> if (isAr) "تسجيل الدخول" else "Connexion"
            "login_desc" -> if (isAr) "نظام إدارة الحضور والغياب المدرسي" else "Système de gestion des présences scolaires"
            "username" -> if (isAr) "اسم المستخدم" else "Nom d'utilisateur"
            "password" -> if (isAr) "كلمة المرور" else "Mot de passe"
            "server_url" -> if (isAr) "رابط الخادم (Server URL)" else "URL du serveur"
            "total_students" -> if (isAr) "إجمالي التلاميذ" else "Total élèves"
            "present" -> if (isAr) "الحاضرون" else "Présents"
            "absent" -> if (isAr) "الغائبون" else "Absents"
            "late" -> if (isAr) "المتأخرون" else "En retard"
            "attendance_rate" -> if (isAr) "نسبة الحضور" else "Taux de présence"
            "recent_scans" -> if (isAr) "آخر عمليات المسح" else "Dernières opérations"
            "by_room" -> if (isAr) "حسب القاعات" else "Par salle"
            "scan_qr" -> if (isAr) "مسح الرمز" else "Scanner le QR"
            "manual_scan" -> if (isAr) "إدخال الرمز يدوياً" else "Saisie manuelle du code"
            "enter_token" -> if (isAr) "أدخل رمز التلميذ (مثال: STU-1254-AB3F7C)" else "Entrez le token (ex: STU-1254-AB3F7C)"
            "quick_test_codes" -> if (isAr) "رموز تجريبية سريعة" else "Codes de test rapides"
            "scan_success" -> if (isAr) "تم تسجيل العملية بنجاح" else "Opération enregistrée avec succès"
            "entry" -> if (isAr) "دخول" else "Entrée"
            "exit" -> if (isAr) "خروج" else "Sortie"
            "search" -> if (isAr) "بحث..." else "Rechercher..."
            "add_student" -> if (isAr) "إضافة تلميذ" else "Ajouter un élève"
            "edit_student" -> if (isAr) "تعديل التلميذ" else "Modifier l'élève"
            "delete_student" -> if (isAr) "حذف التلميذ" else "Supprimer l'élève"
            "first_name" -> if (isAr) "الاسم الشخصي" else "Prénom"
            "last_name" -> if (isAr) "الاسم العائلي" else "Nom"
            "student_id" -> if (isAr) "الرقم التعريفي" else "Matricule"
            "room" -> if (isAr) "القاعة / القسم" else "Salle / Classe"
            "select_room" -> if (isAr) "اختر القاعة" else "Sélectionner la salle"
            "status" -> if (isAr) "الحالة" else "Statut"
            "active" -> if (isAr) "نشط" else "Actif"
            "inactive" -> if (isAr) "غير نشط" else "Inactif"
            "phone" -> if (isAr) "الهاتف" else "Téléphone"
            "parent_phone" -> if (isAr) "هاتف الولي" else "Tél. du tuteur"
            "qr_code" -> if (isAr) "رمز QR" else "Code QR"
            "view_qr" -> if (isAr) "عرض الرمز QR" else "Voir QR Code"
            "add_room" -> if (isAr) "إضافة قاعة" else "Ajouter une salle"
            "edit_room" -> if (isAr) "تعديل القاعة" else "Modifier la salle"
            "room_name" -> if (isAr) "اسم القاعة" else "Nom de la salle"
            "level" -> if (isAr) "المستوى" else "Niveau"
            "section" -> if (isAr) "القسم / الشعبة" else "Section"
            "capacity" -> if (isAr) "الطاقة الاستيعابية" else "Capacité"
            "period" -> if (isAr) "الفترة" else "Période"
            "daily" -> if (isAr) "يومي" else "Quotidien"
            "weekly" -> if (isAr) "أسبوعي" else "Hebdomadaire"
            "monthly" -> if (isAr) "شهري" else "Mensuel"
            "date" -> if (isAr) "التاريخ" else "Date"
            "avg_rate" -> if (isAr) "معدل الحضور" else "Taux moyen"
            "present_per_day" -> if (isAr) "معدل الحضور اليومي" else "Présents/jour"
            "days_present" -> if (isAr) "أيام الحضور" else "Jours présent"
            "days_absent" -> if (isAr) "أيام الغياب" else "Jours absent"
            "most_absent" -> if (isAr) "قائمة الغيابات" else "Classement des absences"
            "site_name_ar" -> if (isAr) "اسم المؤسسة (بالعربية)" else "Nom de l'établissement (Arabe)"
            "site_name_fr" -> if (isAr) "اسم المؤسسة (بالفرنسية)" else "Nom de l'établissement (Français)"
            "primary_color" -> if (isAr) "اللون الأساسي" else "Couleur principale"
            "secondary_color" -> if (isAr) "اللون الثانوي" else "Couleur secondaire"
            "footer_text" -> if (isAr) "نص التذييل" else "Texte de pied de page"
            "save" -> if (isAr) "حفظ التغييرات" else "Enregistrer"
            "cancel" -> if (isAr) "إلغاء" else "Annuler"
            "delete" -> if (isAr) "حذف" else "Supprimer"
            "confirm_delete" -> if (isAr) "هل أنت متأكد من الحذف؟" else "Êtes-vous sûr de vouloir supprimer ?"
            "loading" -> if (isAr) "جارٍ التحميل..." else "Chargement..."
            "empty_data" -> if (isAr) "لا توجد بيانات حالياً" else "Aucune donnée disponible"
            "no_scans" -> if (isAr) "لم يتم تسجيل أي مسح اليوم" else "Aucun scan aujourd'hui"
            "quick_login_hint" -> if (isAr) "بيانات الدخول الافتراضية: admin / Admin@1234" else "Identifiants par défaut : admin / Admin@1234"
            else -> key
        }
    }
}
